services:
  my_service:
    image: elm-build-image # Use your existing image name here
    container_name: elm-fates # Specify your custom container name
    hostname: docker
    user: elm-user # Run the container as the non-root user
    volumes:
      - type: bind
        source: ${PROJECT_DIRECTORY}
        target: /projects_mirror
    stdin_open: true
    tty: true

volumes:
  projects:
